package com.jp.agrodata.jpagrodata.models.enums;

public enum EnumEscolaridade {
    ANALFABETO,
    ALFABETIZADO,
    ENSINO_FUNDAMENTAL,
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_MEDIO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_SUPERIOR,
    ENSINO_SUPERIOR_INCOMPLETO
}
